-- ПравоСправка v2: выполнить целиком в Supabase SQL Editor.
-- После создания первого аккаунта добавьте его UUID в profiles с role='admin'.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.laws (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  type text not null,
  number text,
  date date,
  status text not null default 'Действует',
  tags text[] not null default '{}',
  description text,
  current_text text not null,
  version integer not null default 1,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.law_revisions (
  id bigint generated by default as identity primary key,
  law_id uuid not null references public.laws(id) on delete cascade,
  version integer not null,
  title text not null,
  type text not null,
  number text,
  date date,
  status text not null,
  tags text[] not null default '{}',
  description text,
  text text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id),
  change_note text
);

create index if not exists laws_search_idx on public.laws using gin (to_tsvector('russian', coalesce(title,'')||' '||coalesce(number,'')||' '||coalesce(description,'')||' '||coalesce(current_text,'')));

alter table public.profiles enable row level security;
alter table public.laws enable row level security;
alter table public.law_revisions enable row level security;

drop policy if exists "profiles own read" on public.profiles;
create policy "profiles own read" on public.profiles for select to authenticated using (id = auth.uid());

drop policy if exists "laws public read" on public.laws;
create policy "laws public read" on public.laws for select using (true);

drop policy if exists "laws admin insert" on public.laws;
create policy "laws admin insert" on public.laws for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "laws admin update" on public.laws;
create policy "laws admin update" on public.laws for update to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "laws admin delete" on public.laws;
create policy "laws admin delete" on public.laws for delete to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "revisions public read" on public.law_revisions;
create policy "revisions public read" on public.law_revisions for select using (true);

drop policy if exists "revisions admin insert" on public.law_revisions;
create policy "revisions admin insert" on public.law_revisions for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- Профиль создаётся автоматически после регистрации.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,email) values(new.id,new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Автоматически сохраняем старую редакцию перед изменением документа.
create or replace function public.save_law_revision()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.law_revisions(law_id,version,title,type,number,date,status,tags,description,text,changed_by,change_note)
  values(old.id,old.version,old.title,old.type,old.number,old.date,old.status,old.tags,old.description,old.current_text,auth.uid(),'Предыдущая редакция');
  new.version := old.version + 1;
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists before_law_update on public.laws;
create trigger before_law_update before update on public.laws
for each row execute procedure public.save_law_revision();

-- Для первого администратора:
-- 1) Зарегистрируйтесь на сайте.
-- 2) Выполните:
-- update public.profiles set role='admin' where id='ВАШ-UUID';
-- UUID можно посмотреть в Authentication -> Users.
